dist: trusty
language: c
compiler:
  - gcc

before_script:
  - echo $PWD
  - wget https://allg.one/gXwe -O gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2 && tar xjf gcc-arm-none-eabi-7-2017-q4-major-linux.tar.bz2
  - export PATH=$PATH:$PWD/gcc-arm-none-eabi-7-2017-q4-major/bin
  - arm-none-eabi-gcc --version
  - make --version
  - nproc

script:
  - make EXTRA_CFLAGS=-Werror alltargets -j2

branches:
  only:
  - master
